// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimesheetImport.Data;

#nullable disable

namespace TimesheetImport.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240517190835_InitialDBStructure")]
    partial class InitialDBStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TimesheetImport.Models.DailyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AnnualLeave")
                        .HasColumnType("float");

                    b.Property<double>("CompTime")
                        .HasColumnType("float");

                    b.Property<DateTime>("DayDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("HoursWorked")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("InTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("LunchIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("LunchOut")
                        .HasColumnType("time");

                    b.Property<double>("OtherLeave")
                        .HasColumnType("float");

                    b.Property<double>("OtherLeaveHR")
                        .HasColumnType("float");

                    b.Property<TimeSpan?>("OutTime")
                        .HasColumnType("time");

                    b.Property<double>("OverTime")
                        .HasColumnType("float");

                    b.Property<double>("SickLeave")
                        .HasColumnType("float");

                    b.Property<double>("UHLeave")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeDetailId");

                    b.ToTable("DailyRecords");
                });

            modelBuilder.Entity("TimesheetImport.Models.EmployeeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeKeeper")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeDetails");
                });

            modelBuilder.Entity("TimesheetImport.Models.TimesheetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TimesheetLogs");
                });

            modelBuilder.Entity("TimesheetImport.Models.DailyRecord", b =>
                {
                    b.HasOne("TimesheetImport.Models.EmployeeDetail", null)
                        .WithMany("DailyRecords")
                        .HasForeignKey("EmployeeDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimesheetImport.Models.EmployeeDetail", b =>
                {
                    b.Navigation("DailyRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
